version: '3.3'
services:
    grafana-to-whatsapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: grafana-to-whatsapp
        restart: always
        user: root
        ports:
            - '8001:5000'
#        volumes:
#            - './grafana-to-whatsapp.yml:/etc/grafana-to-whatsapp/grafana-to-whatsapp.yml'
#            - '/opt/grafana-to-whatsapp:/grafana-to-whatsapp'
        image: grafana-to-whatsapp
        networks:
            - monitoring

networks:
    monitoring:
        name: monitoring
        driver: bridge


